# Install script for directory: C:/ncs/v1.6.0/zephyr

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Program Files (x86)/Zephyr-Kernel")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "TRUE")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/zephyr/arch/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/zephyr/lib/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/zephyr/soc/arm/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/zephyr/boards/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/zephyr/subsys/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/zephyr/drivers/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/modules/nrf/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/modules/openthread/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/modules/mcuboot/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/modules/trusted-firmware-m/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/modules/cjson/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/modules/pelion-dm/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/modules/cddl-gen/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/modules/memfault-firmware-sdk/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/modules/cmsis/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/modules/canopennode/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/modules/civetweb/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/modules/fatfs/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/modules/hal_nordic/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/modules/st/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/modules/libmetal/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/modules/lvgl/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/modules/mbedtls/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/modules/mcumgr/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/modules/open-amp/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/modules/loramac-node/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/modules/segger/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/modules/tinycbor/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/modules/tinycrypt/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/modules/littlefs/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/modules/mipi-sys-t/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/modules/nrf_hw_models/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/modules/TraceRecorder/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/modules/nrfxlib/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/modules/connectedhomeip/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/zephyr/kernel/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/zephyr/cmake/flash/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/zephyr/cmake/usage/cmake_install.cmake")
  include("C:/Users/mario/OneDrive/Escritorio/bls-hsm/shell_module_basic/build_nrf5340dk_nrf5340_cpuappns/zephyr/cmake/reports/cmake_install.cmake")

endif()

