CONFIG_HEAP_MEM_POOL_SIZE=448512
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_STDOUT_CONSOLE=y
CONFIG_MBEDTLS=y
CONFIG_MBEDTLS_PKCS5_C=y
CONFIG_HW_CC3XX=y
CONFIG_PSA_CRYPTO_DRIVER_CC3XX=y
CONFIG_NRF_SECURITY=y
CONFIG_MBEDTLS_CIPHER_MODE_CTR=y
CONFIG_MBEDTLS_AES_C=y
CONFIG_MBEDTLS_LEGACY_CRYPTO_C=y
CONFIG_MBEDTLS_ENABLE_HEAP=y